### ISSUE TITLE
Create a contributing guide

### ISSUE THREAD

**Issue by tlarnold10** [DiiiaZoTe/next-route-visualizer#5]
Would be great if there were a contribution guide of some kind. Not sure if that is needed at this point, but it might get more people interested in contributing as well. Just a through, and I would be open to assisting if you need it.

**Comment by DiiiaZoTe** [comment]
Hey, I don't have time to support this at the moment unfortunately. If you wish to make a contribution, feel free to do so! The code is a huge mess in my opinion. I did this really fast and there's a lot of stuff that I would have changed if I were to restart.

**Comment by tlarnold10** [comment]
Created a new PR https://github.com/DiiiaZoTe/next-route-visualizer/pull/6
